In [1]:
import numpy as np

In [3]:
identidad = np.eye(4)
print('Matriz identidad', identidad, sep = '\n\n')

Matriz identidad

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
vector = np.array([[2],[3],[5],[7]])
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [6]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [7]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
inversa_A = np.linalg.inv(A)
print('Matriz', A, ' Matriz Inversa ', inversa_A,  sep = '\n\n')

Matriz

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]

 Matriz Inversa 

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [9]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#cuando no existe la inversa la llamamos matriz singular
singular = np.array([[1,1],[1,1]])
print(singular)

[[1 1]
 [1 1]]


In [11]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix