In [1]:
import numpy as np

In [2]:
escalar = 5.769
vector = np.array([1,2,3])
matriz = np.array([[1,2],
                  [3,4]])
tensor = np.array([
    [[1,2,3],[4,5,6],[6,7,8]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [3]:
print(escalar)

5.769


In [5]:
escalar.shape

AttributeError: 'float' object has no attribute 'shape'

In [9]:
print(vector)
vector.shape

[1 2 3]


(3,)

In [10]:
len(vector)

3

In [13]:
print(matriz)

len(matriz)

[[1 2]
 [3 4]]


2

In [14]:
print(matriz)
matriz.shape

[[1 2]
 [3 4]]


(2, 2)

In [16]:
matriz.size

4

In [22]:
print(tensor)
print(tensor.size)
print(tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
27
(3, 3, 3)


In [23]:
tensor = np.array([
    [[1,2,3],[4,5,6],[6,7,8]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
    [[2,2,2],[2,2,2]]
])

C:\Users\denil\anaconda3\envs\Platzi-FundamentosAL\lib\site-packages\ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """
