In [1]:
import numpy as np 

In [13]:
escalar = 5.769
vector = np.array([1,2,3])
matriz = np.array([[1,2],
                  [3,4],
                 [5,6]])
tensor = np.array([
    [[1,2,3,30], [4,5,6,31], [7,8,9,32]],
    [[11,12,13,33], [14,15,16,34], [17,18,19,35]],
    [[21,22,23,36], [24,25,26,37], [27,28,29,38]]
])

In [3]:
#Un escalar no tiene transpuesta
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [5]:
vector_t = vector.T
print(vector_t) #no veremos una diferencia salvo hagamos cuentas

[1 2 3]


In [9]:
matriz_t = matriz.T
print(matriz_t)
print('------')
print(matriz)

[[1 3 5]
 [2 4 6]]
------
[[1 2]
 [3 4]
 [5 6]]


In [14]:
tensor_t = tensor.T
print(tensor_t)
print('----------------------------')
print(tensor)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]
----------------------------
[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [15]:
A = matriz #(2,3)
B= matriz_t #(3,2)
A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [19]:
A = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

B = np.array([[10,10,10],
             [10,10,10],
             [10,10,10]])
C = A + B

print(A, ' + ', B, ' = ', C, sep = "\n\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 + 

[[10 10 10]
 [10 10 10]
 [10 10 10]]

 = 

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [21]:
D = matriz + escalar
print(matriz, ' + ', escalar, ' = ', D, sep = "\n\n")

[[1 2]
 [3 4]
 [5 6]]

 + 

5.769

 = 

[[ 6.769  7.769]
 [ 8.769  9.769]
 [10.769 11.769]]
