In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = vector  + matriz # sumamos (3) + (3,2)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [6]:
A = vector  + matriz.T # sumamos (3) + (2,3)
print(vector, ' + ', matriz.T, ' = ', A, sep = "\n\n")

[3 4 5]

 + 

[[1 3 5]
 [2 4 6]]

 = 

[[ 4  7 10]
 [ 5  8 11]]


In [ ]:
#Broadcasting extiende la dimension de menor tamano