In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = matriz * vector

In [4]:
B = matriz.dot(vector)

In [5]:
print('Matriz * Vector ', A , ' Producto punto ', B, sep = "\n\n")

Matriz * Vector 

[[ 2  6]
 [ 6 12]
 [10 18]]

 Producto punto 

[ 8 18 28]


In [6]:
B = matriz.dot(vector)
C = np.dot(matriz,vector)

In [7]:
print( 'Opcion 1 ', B, ' Opcion 2 ', C, sep = "\n\n")

Opcion 1 

[ 8 18 28]

 Opcion 2 

[ 8 18 28]
