In [1]:
import numpy as np

In [3]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [6]:
# Asociativa
ABC = A.dot(B.dot(C))
AB_C = A.dot(B).dot(C)
print('ABC ', ABC, ' AB_C ', AB_C, sep = '\n\n')

ABC 

[[ 60  26]
 [145  63]
 [295 129]]

 AB_C 

[[ 60  26]
 [145  63]
 [295 129]]


In [9]:
#Disrtributiva
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))
print('D ', D, ' E ', E,  D==E, sep = '\n\n')

D 

[[ 26  17]
 [ 62  41]
 [122  83]]

 E 

[[ 26  17]
 [ 62  41]
 [122  83]]

[[ True  True]
 [ True  True]
 [ True  True]]


In [10]:
#Conmutativa matrices
F = B.dot(C)
G = C.dot(B)
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

F 

[[15  7]
 [10  4]]

 G 

[[ 5 10]
 [ 8 14]]

[[False False]
 [False False]]


In [11]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

#Conmutativa vectores
v1_tv2 = v1.T.dot(v2) #Se transpone por las dimensiones
v2_tv1 = v2.T.dot(v1)

In [12]:
print('v1_tv2 ', v1_tv2, ' v2_tv1 ', v2_tv1,  v1_tv2 == v2_tv1, sep = '\n\n')

v1_tv2 

[[41]]

 v2_tv1 

[[41]]

[[ True]]
