In [1]:
import numpy as np

In [3]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print('Matriz Diagonal ', matriz, sep ='\n\n')

Matriz Diagonal 

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
print(matriz[0:4,0:3], ' Es diagonal pero no cuadrada ', sep = '\n\n')


[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]

 Es diagonal pero no cuadrada 


In [5]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [6]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [7]:
v1 = np.array([[1,1,1,1]])

print(v1)

print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [8]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [9]:
identidad = A.dot(A_inv)

print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]
